# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run Python Script

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Clone GitHub Actions Repository
        run: |
          git clone --depth=1 https://github.com/actions/upload-artifact.git ~/actions/upload-artifact
        
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || true

      - name: Install Cloudflare Tunnel
        run: |
          curl -fsSL https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cloudflared
          chmod +x cloudflared

      - name: Start Cloudflare Tunnel (Generate Free Domain)
        run: |
          ./cloudflared tunnel --url http://localhost:8080 --no-autoupdate > cloudflare_url.txt 2>&1 &

      - name: Extract Cloudflare Public URL
        run: |
          sleep 5
          cat cloudflare_url.txt | grep -o 'https://[-a-z0-9]*\.cfargotunnel\.com' | tee cloudflare_domain.txt

     
      - name: Run script
        run: python main.py  # Change to your script name


