# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run Python Script

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:  # Allows manual execution

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || true

      - name: Install Cloudflare Tunnel
        run: |
          curl -fsSL https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cloudflared
          chmod +x cloudflared

      - name: Start Cloudflare Tunnel (Generate Free Domain)
        run: |
          ./cloudflared tunnel --url http://localhost:8080 --no-autoupdate > cloudflare_url.txt 2>&1 &

      - name: Extract Cloudflare Public URL
        run: |
          sleep 5
          cat cloudflare_url.txt | grep -o 'https://[-a-z0-9]*\.cfargotunnel\.com' | tee cloudflare_domain.txt

      - name: Store Cloudflare URL as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: cloudflare-url
          path: cloudflare_domain.txt

      
      - name: Run script
        run: python main.py  # Change to your script name


