# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run Python Script

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-20.04
    steps:
      - name: Install OpenVPN
        run: sudo apt-get install -y openvpn

      - name: Set up VPN
        run: |
          echo "${{ secrets.VPN_CONFIG }}" > vpn-config.ovpn
          sudo openvpn --config vpn-config.ovpn &

    
      - name: Checkout Repository
        uses: actions/checkout@v3

      
        
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || true

      

     
      - name: Run script
        run: python main.py  # Change to your script name


